baseURL = "http://localhost:1313/"
title = "Mi sitio web estático en Hugo"
theme = "ssg-i18n"

# Configuración para múltiples idiomas
[languages]
  [languages.es]
    title = "Mi Impresionante Sitio Hugo"
    languageName = "Español"
    weight = 10
    contentDir = "content/es"
    baseURL = "http://localhost:1314/"

  [languages.en]
    title = "My Awesome Hugo Site"
    languageName = "English"
    weight = 20
    contentDir = "content/en"
    baseURL = "http://localhost:1313/"