baseURL = "http://example.org/"
title = "Mi sitio web estático en Hugo"
theme = "ssg-i18n"

# Configuración para múltiples idiomas
[languages]
  [languages.es]
    title = "Mi Impresionante Sitio Hugo"
    languageName = "Español"
    weight = 10 # Orden de aparición, menor peso primero
    baseURL = "http://example.org/" # La raíz es español
    contentDir = "content/es" # Directorio para el contenido en español

  [languages.en]
    title = "My Awesome Hugo Site"
    languageName = "English"
    weight = 20
    baseURL = "http://example.org/en/" # La versión en inglés tendrá un subdirectorio /en/
    contentDir = "content/en" # Directorio para el contenido en inglés